/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/app/**/*.{js,jsx,ts,tsx}", "./src/components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: '#001620',
          dim: '#001620',
          bright: '#233c49',
          'container-lowest': '#001019',
          'container-low': '#021e2a',
          container: '#06222e',
          'container-high': '#132d39',
          'container-highest': '#1e3844',
          tint: '#3cdae2',
          variant: '#1e3844',
        },
        'on-surface': {
          DEFAULT: '#cce6f7',
          variant: '#bbc9ca',
        },
        inverse: {
          surface: '#cce6f7',
          'on-surface': '#1a3340',
          primary: '#00696e',
        },
        outline: {
          DEFAULT: '#859394',
          variant: '#3c494a',
        },
        primary: {
          DEFAULT: '#45e0e8',
          on: '#003739',
          container: '#00c4cc',
          'on-container': '#004c4f',
          fixed: '#63f7ff',
          'fixed-dim': '#3cdae2',
          'on-fixed': '#002021',
          'on-fixed-variant': '#004f53',
        },
        secondary: {
          DEFAULT: '#ffb95f',
          on: '#472a00',
          container: '#ee9800',
          'on-container': '#5b3800',
          fixed: '#ffddb8',
          'fixed-dim': '#ffb95f',
          'on-fixed': '#2a1700',
          'on-fixed-variant': '#653e00',
        },
        tertiary: {
          DEFAULT: '#00e2eb',
          on: '#003739',
          container: '#00c4cc',
          'on-container': '#004c4f',
          fixed: '#61f7ff',
          'fixed-dim': '#00dce4',
          'on-fixed': '#002021',
          'on-fixed-variant': '#004f53',
        },
        error: {
          DEFAULT: '#ffb4ab',
          on: '#690005',
          container: '#93000a',
          'on-container': '#ffdad6',
        },
        background: '#001620',
        'on-background': '#cce6f7',
      },
      fontFamily: {
        display: ["PlusJakartaSans_700Bold", "PlusJakartaSans_600SemiBold"],
        body: ["Inter_400Regular", "Inter_500Medium"],
      },
      fontSize: {
        "display-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        caption: ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
      spacing: {
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '16px',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      }
    },
  },
  plugins: [],
}
